import { Link } from 'react-router-dom';
import { ArrowRight, CircleHelp, Eye, Lightbulb, RotateCcw } from 'lucide-react';
import { AppShell } from '../components/AppShell';
import { useMyEchoes } from '@/features/echoes/hooks';
import type { EchoType } from '@/features/echoes/types';

const meta: Record<EchoType, { label: string; icon: typeof Lightbulb }> = { QUESTION: { label: 'Question', icon: CircleHelp }, CONFUSION: { label: 'Confusion', icon: Eye }, INSIGHT: { label: 'Insight', icon: Lightbulb }, REVIEW: { label: 'Review', icon: RotateCcw } };
const time = (seconds: number) => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;

export function EchoesPage() {
  const query = useMyEchoes();
  return <AppShell><div className="space-y-8"><header><p className="text-sm font-medium text-muted-foreground">Your learning trace</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">My Echoes</h1><p className="mt-2 max-w-2xl text-muted-foreground">A private history of the moments you marked while learning.</p></header>{query.isPending ? <div className="rounded-xl border p-8 text-sm text-muted-foreground">Loading your Echoes…</div> : query.isError ? <div className="rounded-xl border p-8 text-sm text-destructive">Unable to load your Echoes. Please try again.</div> : query.data.length === 0 ? <div className="rounded-xl border p-8 text-center"><h2 className="font-semibold">No Echoes yet</h2><p className="mt-2 text-sm text-muted-foreground">Open a published lesson and mark a moment to create your first Echo.</p><Link to="/classes" className="mt-4 inline-flex rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Browse classes</Link></div> : <section className="space-y-3">{query.data.map((echo) => { const item = meta[echo.type]; const Icon = item.icon; return <article key={echo.id} className="rounded-xl border bg-card p-5"><div className="flex items-start gap-4"><div className="grid size-10 shrink-0 place-items-center rounded-lg bg-muted"><Icon className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><span className="text-sm font-semibold">{item.label}</span><span className="text-xs text-muted-foreground">{time(echo.timestampSeconds)}</span><span className="text-xs text-muted-foreground">{new Date(echo.createdAt).toLocaleDateString()}</span></div>{echo.note && <p className="mt-3 rounded-lg bg-muted/60 p-3 text-sm leading-6">{echo.note}</p>}<Link to={`/lessons/${echo.lessonId}?t=${Math.floor(echo.timestampSeconds)}`} className="mt-4 inline-flex items-center gap-1.5 text-sm font-medium hover:underline">Open lesson <ArrowRight className="size-4" /></Link></div></div></article>; })}</section>}</div></AppShell>;
}
