import { ArrowRight, BookOpen, Brain, ChartNoAxesCombined, CheckCircle2, CircleHelp, Lightbulb, Play, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

const features = [
  { icon: CircleHelp, title: 'Timestamped Echoes', description: 'Mark the exact second when something feels confusing, important, or worth remembering.' },
  { icon: ChartNoAxesCombined, title: 'Learning Timeline', description: 'Turn reactions into a visual trace that makes meaningful moments easier to find again.' },
  { icon: Brain, title: 'Focused Revisits', description: 'Return to the moment you need without searching through an entire lesson.' },
  { icon: Lightbulb, title: 'Classroom Insight', description: 'Help teachers notice where attention, questions, and understanding begin to cluster.' },
];

const steps = [
  ['01', 'Watch', 'Follow the lesson normally and stay focused on the idea in front of you.'],
  ['02', 'Echo', 'Leave a lightweight signal when a specific moment deserves attention.'],
  ['03', 'Revisit', 'Come back to the exact moment later with the context still attached.'],
];

export function LandingPage() {
  return <main className="overflow-hidden bg-background text-foreground">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><Link to="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Sparkles size={18} /></span>EchoClass</Link><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#product">Product</a><a href="#how-it-works">How it works</a><a href="#for-everyone">For your classroom</a></nav><div className="flex gap-2"><Link to="/login" className="rounded-lg px-3 py-2 text-sm font-medium hover:bg-muted">Sign in</Link><Link to="/register" className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Get started</Link></div></header>
    <section className="mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-12 sm:px-8 sm:pb-28 sm:pt-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-10"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border bg-card px-3 py-1.5 text-xs font-medium text-muted-foreground"><span className="size-1.5 rounded-full bg-[var(--green)]" />A calmer way to learn from video</div><h1 className="text-5xl font-semibold tracking-[-0.045em] sm:text-6xl lg:text-7xl">Learn actively.<br /><span className="text-[var(--amber)]">Remember what matters.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">EchoClass helps students leave lightweight signals at the exact moments that matter, so important ideas are easier to revisit later.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Get started <ArrowRight size={16} /></Link><Link to="/login" className="rounded-xl border bg-card px-5 py-3 text-sm font-semibold">Sign in</Link></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground"><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-[var(--green)]" />Mark exact learning moments</span><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-[var(--green)]" />Revisit with context</span></div></div><div className="rounded-[2rem] border bg-card p-4 shadow-2xl sm:p-5"><div className="flex items-center justify-between px-2 pb-4"><div><p className="text-xs text-muted-foreground">Introduction to Physics</p><h2 className="mt-1 font-semibold">Force and acceleration</h2></div><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-medium">12:42</span></div><div className="relative aspect-[16/10] overflow-hidden rounded-2xl bg-[linear-gradient(135deg,#1B2A4A,#31496E)] p-6 text-white"><div className="flex h-full flex-col justify-between"><div className="flex items-center gap-2 text-xs text-white/70"><BookOpen size={15} />Lesson moment</div><div className="grid size-14 place-items-center rounded-full bg-white/15"><Play size={23} fill="currentColor" /></div><div><div className="h-1.5 overflow-hidden rounded-full bg-white/20"><div className="h-full w-[48%] rounded-full bg-[var(--amber)]" /></div><div className="mt-2 flex justify-between text-[11px] text-white/60"><span>12:42</span><span>26:18</span></div></div></div></div><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-xl border bg-[#FFF2E5] p-3 text-center">😕<p className="mt-1 text-xs font-medium">Confused</p></div><div className="rounded-xl border bg-secondary p-3 text-center">⭐<p className="mt-1 text-xs font-medium">Important</p></div><div className="rounded-xl border bg-[rgba(92,184,138,.13)] p-3 text-center">💡<p className="mt-1 text-xs font-medium">Insight</p></div></div></div></section>
    <section className="border-y bg-card"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-8 sm:grid-cols-3 sm:px-8 lg:px-10">{[['Capture the moment','Leave a signal without breaking your flow.'],['See what matters','Build a visible trace through every lesson.'],['Revisit with context','Return to the exact point when you need it.']].map(([title, description]) => <div key={title}><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>)}</div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10"><p className="text-sm font-semibold text-[var(--amber)]">HOW IT WORKS</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">A simple learning loop that stays out of the way.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{steps.map(([number, title, description]) => <article key={number} className="rounded-2xl border bg-card p-6"><span className="text-sm font-semibold text-[var(--amber)]">{number}</span><h3 className="mt-10 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{description}</p></article>)}</div></section>
    <section id="product" className="bg-muted/70"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10"><p className="text-sm font-semibold text-[var(--amber)]">BUILT FOR THE LESSON</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">Everything points back to a meaningful moment.</h2><div className="mt-12 grid gap-4 md:grid-cols-2">{features.map(({ icon: Icon, title, description }) => <article key={title} className="rounded-2xl border bg-card p-6"><div className="grid size-11 place-items-center rounded-xl bg-secondary"><Icon size={21} /></div><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 leading-7 text-muted-foreground">{description}</p></article>)}</div></div></section>
    <section id="for-everyone" className="mx-auto grid max-w-7xl gap-5 px-5 py-24 sm:px-8 md:grid-cols-2 lg:px-10"><article className="rounded-3xl bg-primary p-8 text-primary-foreground sm:p-10"><p className="text-sm font-semibold text-[var(--amber)]">FOR STUDENTS</p><h2 className="mt-4 text-3xl font-semibold tracking-tight">Understand what to revisit without losing your place.</h2><p className="mt-5 leading-7 text-white/70">Capture uncertainty and insight in the moment, then come back when you are ready to learn from it.</p></article><article className="rounded-3xl border bg-card p-8 sm:p-10"><p className="text-sm font-semibold text-[var(--green)]">FOR TEACHERS</p><h2 className="mt-4 text-3xl font-semibold tracking-tight">See where the class needs attention.</h2><p className="mt-5 leading-7 text-muted-foreground">Notice patterns around the lesson without interrupting the flow of teaching or asking students to switch contexts.</p></article></section>
    <section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-10"><div className="rounded-[2rem] border bg-[linear-gradient(135deg,var(--chalk),#fff)] px-6 py-16 text-center"><p className="text-sm font-semibold text-[var(--amber)]">READY TO BEGIN</p><h2 className="mx-auto mt-4 max-w-2xl text-3xl font-semibold tracking-tight sm:text-5xl">Make every lesson easier to return to.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-muted-foreground">Start building a learning trace around the moments that deserve another look.</p><div className="mt-8 flex justify-center gap-3"><Link to="/register" className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Create your account <ArrowRight size={16} /></Link><Link to="/login" className="rounded-xl border bg-card px-5 py-3 text-sm font-semibold">Sign in</Link></div></div></section>
    <footer className="border-t"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-10"><div><p className="font-semibold">EchoClass</p><p className="mt-1 text-muted-foreground">Every lesson leaves a trace.</p></div><div className="flex gap-5 text-muted-foreground"><Link to="/login">Sign in</Link><Link to="/register">Get started</Link></div></div></footer>
  </main>;
}
