import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, BookOpen, Copy, MoreHorizontal, Pencil, Plus, Settings, Users } from 'lucide-react';
import { AppShell } from '../components/AppShell';

const classData = {
  physics: {
    name: 'Introduction to Physics', description: 'Build intuition for motion, forces, energy, and the ideas underneath them.', invite: 'PHY-7K4P2', students: 28,
    lessons: [{ title: 'Motion is a story of change', status: 'Published', duration: '38 min' }, { title: 'Forces and why things move', status: 'Published', duration: '42 min' }, { title: 'Where does energy go?', status: 'Draft', duration: '35 min' }],
    activity: [{ text: '14 Echoes were added to Forces and why things move', when: 'Today' }, { text: '22 students opened Motion is a story of change', when: 'Yesterday' }, { text: '3 students joined the class', when: '2 days ago' }],
  },
  history: {
    name: 'Modern World History', description: 'Trace the people, movements, and turning points that shaped the modern world.', invite: 'HIS-3M8Q1', students: 24,
    lessons: [{ title: 'The world connected by trade', status: 'Published', duration: '31 min' }, { title: 'Ideas that changed societies', status: 'Published', duration: '44 min' }, { title: 'The industrial age', status: 'Draft', duration: '39 min' }],
    activity: [{ text: '11 Echoes were added to The world connected by trade', when: 'Today' }, { text: '19 students opened Ideas that changed societies', when: 'Yesterday' }],
  },
};

export function TeacherClassPage() {
  const { classId = 'physics' } = useParams();
  const data = classData[classId as keyof typeof classData] ?? classData.physics;

  return <AppShell><div className="space-y-8">
    <Link to="/teacher/dashboard" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Teacher dashboard</Link>
    <header className="rounded-2xl border bg-card p-6 sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-medium text-muted-foreground">Class management</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{data.name}</h1><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">{data.description}</p></div><div className="flex flex-wrap gap-2"><Link to={`/teacher/classes/${classId}/lessons/new`} className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm font-medium text-primary-foreground"><Plus className="size-4" />Create Lesson</Link><button type="button" className="inline-flex items-center gap-2 rounded-lg border bg-background px-3 py-2 text-sm font-medium hover:bg-muted"><Pencil className="size-4" />Edit Class</button></div></div></header>
    <section className="grid gap-4 sm:grid-cols-2"><article className="rounded-xl border bg-card p-5"><Users className="size-5 text-muted-foreground" /><p className="mt-4 text-2xl font-semibold">{data.students}</p><p className="mt-1 text-sm text-muted-foreground">Students enrolled</p><Link to={`/teacher/classes/${classId}/students`} className="mt-4 inline-flex text-sm font-medium hover:underline">Manage students</Link></article><article className="rounded-xl border bg-card p-5"><BookOpen className="size-5 text-muted-foreground" /><p className="mt-4 text-2xl font-semibold">{data.lessons.length}</p><p className="mt-1 text-sm text-muted-foreground">Lessons</p><Link to={`/teacher/classes/${classId}/lessons`} className="mt-4 inline-flex text-sm font-medium hover:underline">Manage lessons</Link></article></section>
    <section className="rounded-xl border bg-card p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Invite code</h2><p className="mt-1 text-sm text-muted-foreground">Share this code with students who need to join the class.</p></div><button type="button" aria-label="More invite code actions" className="rounded-lg p-2 hover:bg-muted"><MoreHorizontal className="size-5" /></button></div><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center"><code className="rounded-lg border bg-muted px-4 py-3 text-lg font-semibold tracking-[0.18em]">{data.invite}</code><button type="button" className="inline-flex items-center justify-center gap-2 rounded-lg border bg-background px-3 py-2 text-sm font-medium hover:bg-muted"><Copy className="size-4" />Copy code</button></div></section>
    <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-lg font-semibold">Lessons</h2><p className="mt-1 text-sm text-muted-foreground">Manage content and publication state.</p></div><Link to={`/teacher/classes/${classId}/lessons`} className="text-sm font-medium hover:underline">View all</Link></div><div className="space-y-3">{data.lessons.map((lesson) => <div key={lesson.title} className="flex items-center gap-4 rounded-xl border bg-card p-4"><div className="grid size-10 shrink-0 place-items-center rounded-lg bg-secondary"><BookOpen className="size-4" /></div><div className="min-w-0 flex-1"><p className="font-medium">{lesson.title}</p><p className="mt-1 text-xs text-muted-foreground">{lesson.duration}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${lesson.status === 'Published' ? 'bg-[#EEF9F3] text-[#286846]' : 'bg-[#FFF2E5] text-[#8A541F]'}`}>{lesson.status}</span><button type="button" aria-label={`Actions for ${lesson.title}`} className="rounded-lg p-2 hover:bg-muted"><MoreHorizontal className="size-4" /></button></div>)}</div></section>
    <section className="rounded-xl border bg-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Recent activity</h2><p className="mt-1 text-sm text-muted-foreground">A lightweight classroom pulse, not a leaderboard.</p></div><Settings className="size-5 text-muted-foreground" /></div><div className="mt-5 space-y-4">{data.activity.map((item) => <div key={item.text} className="flex gap-3 border-b pb-4 last:border-0 last:pb-0"><span className="mt-1 size-2 shrink-0 rounded-full bg-[#5CB88A]" /><div className="flex-1"><p className="text-sm">{item.text}</p><p className="mt-1 text-xs text-muted-foreground">{item.when}</p></div></div>)}</div></section>
  </div></AppShell>;
}
