import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, BarChart3, BookOpen, MoreHorizontal, Pencil, Plus, Upload, Archive } from 'lucide-react';
import { AppShell } from '../components/AppShell';

const lessons = [
  { id: 'motion', title: 'Motion is a story of change', status: 'Published', duration: '38 min', updated: 'Today' },
  { id: 'forces', title: 'Forces and why things move', status: 'Published', duration: '42 min', updated: 'Yesterday' },
  { id: 'energy', title: 'Where does energy go?', status: 'Draft', duration: '35 min', updated: '2 days ago' },
];

export function TeacherLessonsPage() {
  const { classId = 'physics' } = useParams();
  return <AppShell><div className="space-y-8">
    <Link to={`/teacher/classes/${classId}`} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Class management</Link>
    <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-muted-foreground">Lesson management</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Lessons</h1><p className="mt-2 text-muted-foreground">Create, review, publish, and manage the lessons in this class.</p></div><Link to={`/teacher/classes/${classId}/lessons/new`} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground"><Plus className="size-4" />Create Lesson</Link></header>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">Total lessons</p><p className="mt-1 text-2xl font-semibold">{lessons.length}</p></div><div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">Published</p><p className="mt-1 text-2xl font-semibold">{lessons.filter((l) => l.status === 'Published').length}</p></div><div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">Drafts</p><p className="mt-1 text-2xl font-semibold">{lessons.filter((l) => l.status === 'Draft').length}</p></div></div>
    <section className="space-y-3">{lessons.map((lesson) => <article key={lesson.id} className="rounded-xl border bg-card p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="grid size-11 shrink-0 place-items-center rounded-lg bg-secondary"><BookOpen className="size-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{lesson.title}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${lesson.status === 'Published' ? 'bg-[#EEF9F3] text-[#286846]' : 'bg-[#FFF2E5] text-[#8A541F]'}`}>{lesson.status}</span></div><p className="mt-1 text-sm text-muted-foreground">{lesson.duration} · Updated {lesson.updated}</p></div><div className="flex flex-wrap gap-2"><Link to={`/lessons/${lesson.id}`} className="inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-sm font-medium hover:bg-muted"><BookOpen className="size-4" />Open</Link><Link to={`/teacher/classes/${classId}/lessons/${lesson.id}/edit`} className="inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-sm font-medium hover:bg-muted"><Pencil className="size-4" />Edit</Link><Link to={`/teacher/classes/${classId}/lessons/${lesson.id}/analytics`} className="inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-sm font-medium hover:bg-muted"><BarChart3 className="size-4" />Analytics</Link><button type="button" aria-label={`More actions for ${lesson.title}`} className="rounded-lg border p-2 hover:bg-muted"><MoreHorizontal className="size-4" /></button></div></div>{lesson.status === 'Draft' && <div className="mt-4 flex flex-wrap gap-2 border-t pt-4"><Link to={`/teacher/classes/${classId}/lessons/${lesson.id}/upload`} className="inline-flex items-center gap-1.5 text-sm font-medium hover:underline"><Upload className="size-4" />Upload video</Link><button type="button" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"><Archive className="size-4" />Archive draft</button></div>}</article>)}</section>
  </div></AppShell>;
}
