import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { AppShell } from '../components/AppShell';
import { useAuth } from '../auth/useAuth';
import { apiClient } from '../../lib/api/client';

export function TeacherCreateLessonPage() {
  const { classId } = useParams(); const navigate = useNavigate(); const { getAccessToken } = useAuth(); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const token = await getAccessToken(); if (!token || !classId) throw new Error('Your session has expired.'); const result = await apiClient.post<{ lesson: { id: string } }>(`/classes/${classId}/lessons`, { title: title.trim(), description: description.trim() || undefined }, token); navigate(`/lessons/${result.lesson.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to create lesson.'); } finally { setSaving(false); } }
  return <AppShell><div className="mx-auto max-w-2xl space-y-8"><Link to={`/teacher/classes/${classId}`} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Class management</Link><header><p className="text-sm font-medium text-muted-foreground">Lesson management</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Create lesson</h1><p className="mt-2 text-muted-foreground">Create the lesson record first. Video upload and publishing can follow.</p></header>{error && <div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}<form onSubmit={submit} className="space-y-5 rounded-2xl border bg-card p-6"><label className="block"><span className="text-sm font-medium">Title</span><input required maxLength={160} value={title} onChange={(event) => setTitle(event.target.value)} className="mt-2 w-full rounded-lg border bg-background px-3 py-2.5 text-sm" placeholder="e.g. Introduction to motion" /></label><label className="block"><span className="text-sm font-medium">Description</span><textarea maxLength={2000} value={description} onChange={(event) => setDescription(event.target.value)} className="mt-2 min-h-32 w-full rounded-lg border bg-background px-3 py-2.5 text-sm" placeholder="What will students learn?" /></label><div className="flex justify-end gap-2"><Link to={`/teacher/classes/${classId}`} className="rounded-lg border px-4 py-2.5 text-sm font-medium">Cancel</Link><button disabled={saving} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground disabled:opacity-50">{saving ? 'Creating…' : 'Create lesson'}</button></div></form></div></AppShell>;
}
