import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, BookOpen, MoreHorizontal, Plus } from 'lucide-react';
import { AppShell } from '../components/AppShell';
import { EmptyState } from '../components/EmptyState';
import { useAuth } from '../auth/useAuth';
import { apiClient } from '../../lib/api/client';
import { useEffect, useState } from 'react';

type Lesson = { id: string; title: string; description?: string | null; status: string };
export function TeacherLessonsPage() {
  const { classId } = useParams(); const { getAccessToken } = useAuth(); const [lessons, setLessons] = useState<Lesson[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void (async () => { try { const token = await getAccessToken(); if (!token || !classId) throw new Error('Unable to load lessons.'); setLessons((await apiClient.get<{ lessons: Lesson[] }>(`/classes/${classId}/lessons`, token)).lessons); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load lessons.'); } finally { setLoading(false); } })(); }, [classId]);
  return <AppShell><div className="space-y-8"><Link to={`/teacher/classes/${classId}`} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Class management</Link><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-muted-foreground">Lesson management</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Lessons</h1><p className="mt-2 text-muted-foreground">Manage the lessons in this class.</p></div><Link to={`/teacher/classes/${classId}/lessons/new`} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground"><Plus className="size-4" />Create Lesson</Link></header>{error && <div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}{loading ? <div className="rounded-xl border bg-card p-6 text-sm text-muted-foreground">Loading lessons…</div> : lessons.length === 0 ? <EmptyState title="No lessons yet" description="Create your first lesson for this class. Video upload can be added after the lesson exists." action={<Link to={`/teacher/classes/${classId}/lessons/new`} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Create lesson</Link>} /> : <section className="space-y-3">{lessons.map((lesson) => <article key={lesson.id} className="rounded-xl border bg-card p-5"><div className="flex items-center gap-4"><div className="grid size-11 shrink-0 place-items-center rounded-lg bg-secondary"><BookOpen className="size-5" /></div><div className="min-w-0 flex-1"><h2 className="font-semibold">{lesson.title}</h2><p className="mt-1 text-sm text-muted-foreground">{lesson.status} · {lesson.description ?? 'No description'}</p></div><Link to={`/lessons/${lesson.id}`} className="rounded-lg border p-2 hover:bg-muted" aria-label={`Open ${lesson.title}`}><MoreHorizontal className="size-4" /></Link></div></article>)}</section>}</div></AppShell>;
}
