import { useState, type ReactNode } from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import { BookOpen, ChevronDown, ClipboardList, Home, LogOut, MessageCircle, Settings, User } from 'lucide-react';
import { useAuth } from '../auth/useAuth';
import { EchoClassLogo } from './EchoClassLogo';
const navigation = [{ to: '/dashboard', label: 'Dashboard', icon: Home }, { to: '/classes', label: 'Classes', icon: BookOpen }, { to: '/echoes', label: 'My Echoes', icon: MessageCircle }, { to: '/revisits', label: 'Revisit', icon: ClipboardList }, { to: '/profile', label: 'Profile', icon: User }];
function Brand({ compact = false }: { compact?: boolean }) { return <div className="flex items-center gap-3"><EchoClassLogo className={compact ? 'size-8' : 'size-10'} /><div><div className="font-semibold tracking-tight text-foreground">EchoClass</div><div className="mt-0.5 text-xs text-muted-foreground">Every lesson leaves a trace.</div></div></div>; }
export function AppShell({ children }: { children: ReactNode }) { const navigate = useNavigate(); const { user, signOut } = useAuth(); const [menuOpen, setMenuOpen] = useState(false); const email = user?.email ?? user?.username ?? 'Account'; const initials = (user?.name ?? email).split(/\s+/).map(part => part[0]).join('').slice(0, 2).toUpperCase() || 'EC'; async function logout() { await signOut(); navigate('/login'); }
return <div className="min-h-screen bg-background text-foreground"><aside className="fixed inset-y-0 left-0 z-20 hidden w-64 border-r bg-sidebar px-5 py-7 lg:block"><NavLink to="/dashboard" className="mb-10 block px-3"><Brand /></NavLink><nav className="space-y-1" aria-label="Primary navigation">{navigation.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} className={({ isActive }) => `flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition ${isActive ? 'bg-sidebar-accent font-medium text-sidebar-accent-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="size-4" />{label}</NavLink>)}</nav></aside><header className="sticky top-0 z-30 border-b bg-background/95 backdrop-blur lg:ml-64"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5 sm:px-8"><div className="lg:hidden"><Brand compact /></div><div className="relative ml-auto"><button type="button" onClick={() => setMenuOpen(o => !o)} className="flex items-center gap-2 rounded-lg p-1.5 hover:bg-muted"><div className="grid size-9 place-items-center rounded-full bg-primary text-sm font-semibold text-primary-foreground">{initials}</div><div className="hidden text-left sm:block"><p className="text-sm font-medium">{user?.name ?? 'EchoClass user'}</p><p className="text-xs text-muted-foreground">Account</p></div><ChevronDown className="size-4 text-muted-foreground" /></button>{menuOpen && <div role="menu" className="absolute right-0 mt-2 w-56 rounded-xl border bg-popover p-1.5 shadow-lg"><div className="border-b px-3 py-2.5"><p className="text-sm font-medium">{user?.name ?? 'EchoClass user'}</p><p className="truncate text-xs text-muted-foreground">{email}</p></div><button role="menuitem" onClick={() => { setMenuOpen(false); navigate('/settings'); }} className="mt-1 flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm hover:bg-muted"><Settings className="size-4" />Settings</button><button role="menuitem" onClick={logout} className="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm text-destructive hover:bg-destructive/10"><LogOut className="size-4" />Log out</button></div>}</div></div></header><main className="lg:ml-64"><div className="mx-auto w-full max-w-6xl px-5 py-8 sm:px-8 sm:py-10">{children}</div></main><nav className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-5 border-t bg-sidebar/95 p-2 backdrop-blur lg:hidden" aria-label="Mobile navigation">{navigation.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} className={({ isActive }) => `flex flex-col items-center gap-1 rounded-md py-2 text-[11px] ${isActive ? 'font-medium text-foreground' : 'text-muted-foreground'}`}><Icon className="size-4" />{label}</NavLink>)}</nav></div>; }
