import { verifyBearerToken } from './auth.mjs';
import { getOrCreateUser } from './user-repository.mjs';
import { getClassForStudent } from './class-repository.mjs';
import { getLessonById } from './lesson-repository.mjs';
import { createEcho, deleteEcho, listEchoesForStudent, updateEcho } from './echo-repository.mjs';

const corsHeaders = { 'access-control-allow-origin': 'http://localhost:5173', 'access-control-allow-methods': 'GET,POST,PATCH,DELETE,OPTIONS', 'access-control-allow-headers': 'content-type,authorization' };
const json = (statusCode, body) => ({ statusCode, headers: { ...corsHeaders, 'content-type': 'application/json' }, body: JSON.stringify(body) });
const error = (statusCode, code, message) => Object.assign(new Error(message), { statusCode, code });
const body = (event) => { if (!event.body) return {}; try { return typeof event.body === 'string' ? JSON.parse(event.body) : event.body; } catch { throw error(400, 'INVALID_JSON', 'Request body must be valid JSON'); } };
const header = (headers, name) => { const key = Object.keys(headers ?? {}).find((k) => k.toLowerCase() === name.toLowerCase()); return key ? headers[key] : undefined; };
const pathOf = (event) => (event.rawPath ?? event.path ?? '/').replace(/^\/api\/v1(?=\/|$)/, '').replace(/^\/api(?=\/|$)/, '') || '/';
const parseId = (path) => /^\/lessons\/([^/]+)\/echoes(?:\/([^/]+))?$/.exec(path);
const validate = (input, durationSeconds) => { const timestampSeconds = Number(input.timestampSeconds); const allowed = ['QUESTION', 'CONFUSION', 'INSIGHT', 'REVIEW']; const hasKnownDuration = Number.isFinite(durationSeconds) && durationSeconds > 0; if (!Number.isFinite(timestampSeconds) || timestampSeconds < 0 || (hasKnownDuration && timestampSeconds > durationSeconds)) throw error(400, 'VALIDATION_ERROR', hasKnownDuration ? 'timestampSeconds must be within the lesson duration' : 'timestampSeconds must be a non-negative number'); if (!allowed.includes(input.type)) throw error(400, 'VALIDATION_ERROR', 'Invalid Echo type'); if (input.note !== undefined && input.note !== null && (typeof input.note !== 'string' || input.note.length > 1000)) throw error(400, 'VALIDATION_ERROR', 'note must be at most 1000 characters'); return { timestampSeconds, type: input.type, note: typeof input.note === 'string' ? input.note.trim() || undefined : undefined }; };
const authorizeLesson = async (lessonId, userId) => { const lesson = await getLessonById(lessonId); if (!lesson || lesson.status !== 'PUBLISHED' || !(await getClassForStudent(lesson.classId, userId))) throw error(404, 'NOT_FOUND', 'Lesson not found'); return lesson; };

export const handler = async (event) => { if ((event.requestContext?.http?.method ?? event.httpMethod) === 'OPTIONS') return { statusCode: 204, headers: corsHeaders, body: '' }; try { const principal = await verifyBearerToken(header(event.headers, 'authorization')); const user = await getOrCreateUser(principal); if (user.role !== 'STUDENT') throw error(403, 'FORBIDDEN', 'Only students can manage Echoes'); const method = event.requestContext?.http?.method ?? event.httpMethod ?? 'GET'; const path = pathOf(event); if (method === 'GET' && path === '/echoes') return json(200, { echoes: await listEchoesForStudent(user.userId) }); const route = parseId(path); if (!route) return json(404, { error: { code: 'NOT_FOUND', message: 'Route not found' } }); const [, lessonId, echoId] = route; const lesson = await authorizeLesson(lessonId, user.userId); const duration = Number(lesson.media?.durationSeconds ?? 0); const mine = () => listEchoesForStudent(user.userId).then((echoes) => echoes.filter((echo) => echo.lessonId === lessonId)); if (method === 'GET' && !echoId) return json(200, { echoes: await mine() }); if (method === 'POST' && !echoId) return json(201, { echo: await createEcho({ studentUserId: user.userId, lessonId, ...validate(body(event), duration) }) }); if (method === 'PATCH' && echoId) { const echo = await updateEcho({ echoId, lessonId, studentUserId: user.userId, ...validate(body(event), duration) }); if (!echo) throw error(404, 'NOT_FOUND', 'Echo not found'); return json(200, { echo }); } if (method === 'DELETE' && echoId) { const removed = await deleteEcho({ echoId, lessonId, studentUserId: user.userId }); if (!removed) throw error(404, 'NOT_FOUND', 'Echo not found'); return json(204, {}); } return json(404, { error: { code: 'NOT_FOUND', message: 'Route not found' } }); } catch (e) { const status = e?.statusCode ?? 500; return json(status < 500 ? status : 500, { error: { code: e?.code ?? 'INTERNAL_ERROR', message: status < 500 ? e.message : 'Unable to process request' } }); } };
