import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';

import { apiRequest } from '@/lib/api/client';
import { isCognitoConfigured } from '@/lib/auth/config';
import { cognitoAuth, type AuthRole } from '@/lib/auth/cognito';
import { AuthContext, type AuthUser } from './AuthContext';

type MeResponse = { user: { id: string; username: string; email?: string | null; role?: AuthRole | null; createdAt: string } };
function isMeResponse(value: unknown): value is MeResponse { if (!value || typeof value !== 'object') return false; const user = (value as { user?: unknown }).user; if (!user || typeof user !== 'object') return false; const candidate = user as Record<string, unknown>; return typeof candidate.id === 'string' && typeof candidate.username === 'string'; }

export function AuthProvider({ children }: { children: ReactNode }) {
  const configured = isCognitoConfigured();
  const [isLoading, setIsLoading] = useState(configured);
  const [user, setUser] = useState<AuthUser | null>(() => configured ? cognitoAuth.getCurrentUser() : null);
  const bootstrapApplicationUser = useCallback(async () => { const accessToken = configured ? cognitoAuth.getAccessToken() : null; console.debug('[EchoClass Auth] bootstrap start', { configured, hasAccessToken: Boolean(accessToken) }); if (!accessToken) { setUser(null); return; } const response = await apiRequest<MeResponse>('/api/v1/me', undefined, accessToken); console.debug('[EchoClass Auth] /me response received', response); if (!isMeResponse(response)) throw new Error('Application API returned an invalid /me response'); setUser((current) => ({ userId: response.user.id, username: response.user.username || current?.username || '', email: response.user.email ?? current?.email, name: current?.name, role: response.user.role ?? current?.role })); }, [configured]);
  const refreshUser = useCallback(() => { const current = configured ? cognitoAuth.getCurrentUser() : null; console.debug('[EchoClass Auth] local Cognito session', { configured, authenticated: Boolean(current), userId: current?.userId }); setUser(current); }, [configured]);
  useEffect(() => { let cancelled = false; const initialize = async () => { refreshUser(); try { if (!cancelled) await bootstrapApplicationUser(); } catch (error) { if (!cancelled) console.error('[EchoClass Auth] application-user bootstrap failed', error); } finally { if (!cancelled) setIsLoading(false); } }; void initialize(); return () => { cancelled = true; }; }, [bootstrapApplicationUser, refreshUser]);
  const value = useMemo(() => ({ user, isLoading, isConfigured: configured, async signIn(username: string, password: string) { console.debug('[EchoClass Auth] sign-in start', { username }); await cognitoAuth.signIn(username, password); console.debug('[EchoClass Auth] Cognito sign-in succeeded', { hasAccessToken: Boolean(cognitoAuth.getAccessToken()) }); await bootstrapApplicationUser(); }, async signUp(username: string, password: string, name: string, role: AuthRole) { console.debug('[EchoClass Auth] sign-up start', { username, role }); const result = await cognitoAuth.signUp(username, password, name, role); console.debug('[EchoClass Auth] Cognito sign-up succeeded', { needsConfirmation: !result.isSignUpComplete }); return { needsConfirmation: !result.isSignUpComplete }; }, async confirmSignUp(username: string, code: string) { console.debug('[EchoClass Auth] confirmation start', { username }); await cognitoAuth.confirmSignUp(username, code); console.debug('[EchoClass Auth] Cognito confirmation succeeded', { username }); }, async resendConfirmationCode(username: string) { await cognitoAuth.resendConfirmationCode(username); }, async setRole(role: AuthRole) { await cognitoAuth.setRole(role); await bootstrapApplicationUser(); }, async signOut() { cognitoAuth.signOut(); setUser(null); }, async getAccessToken() { return configured ? cognitoAuth.getAccessToken() : null; } }), [bootstrapApplicationUser, configured, isLoading, user]);
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
